name: nextstrain
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - cvxopt
  - fasttree
  - iqtree
  - mafft
  - opencv
  - pandas
  - python=3
  - nodejs=10
  - raxml
  - vcftools
  - git
  - pip
  - seaborn
  - colour
  - biopython
  - geopy
  - xlrd
  - pip:
    - nextstrain-augur>=7.0.2
    - nextstrain-cli
    - gdown
